import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkgPath = path.resolve(__dirname, '../package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const baseVersion = pkg.version || '1.2.0';

// Determine if running in CI
const isCI = process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true';

// Helper to get git info safely
function getGitOutput(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch (e) {
    return '';
  }
}

let channel = 'dev';
let devName = 'local';
let branchName = 'main';
let buildNumber = 1;
let versionName = baseVersion;
let fullVersionString = baseVersion;

if (!isCI) {
  // Local Developer Build
  channel = 'dev';

  // 1. Developer Handle
  const rawDev = process.env.TMDB_DEV_NAME || 
                 process.env.DEV_NAME || 
                 getGitOutput('git config user.name') || 
                 process.env.USERNAME || 
                 process.env.USER || 
                 'dev';
  devName = rawDev.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 12) || 'dev';

  // 2. Branch Name
  const rawBranch = getGitOutput('git rev-parse --abbrev-ref HEAD') || 'local';
  branchName = rawBranch.toLowerCase().replace(/[^a-z0-9._-]/g, '-').slice(0, 20) || 'main';

  // 3. Local build state
  const statePath = path.resolve(__dirname, '../.build-state.local.json');
  let localState = { buildNumber: pkg.buildNumber || 215 };
  if (fs.existsSync(statePath)) {
    try {
      localState = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    } catch (e) {}
  }
  buildNumber = (localState.buildNumber || pkg.buildNumber || 215) + 1;
  localState.buildNumber = buildNumber;
  localState.lastBuild = new Date().toISOString();
  fs.writeFileSync(statePath, JSON.stringify(localState, null, 2) + '\n', 'utf8');

  versionName = `${baseVersion}-dev.${devName}.${buildNumber}`;
  fullVersionString = `${baseVersion}-dev.${devName}.${branchName}.${buildNumber}`;
} else {
  // CI Build (GitHub Actions)
  const ciEvent = process.env.GITHUB_EVENT_NAME || '';
  const refName = process.env.GITHUB_REF_NAME || '';
  const runNumber = parseInt(process.env.GITHUB_RUN_NUMBER || '1', 10);
  buildNumber = runNumber;

  if (process.env.BUILD_CHANNEL === 'nightly' || ciEvent === 'schedule') {
    channel = 'nightly';
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
    versionName = `${baseVersion}-nightly.${dateStr}.${runNumber}`;
    fullVersionString = versionName;
  } else if (refName.includes('-rc.') || refName.includes('-rc')) {
    channel = 'rc';
    const cleanTag = refName.replace(/^v/, '');
    versionName = cleanTag;
    fullVersionString = cleanTag;
  } else if (refName.startsWith('v')) {
    channel = 'stable';
    const cleanTag = refName.replace(/^v/, '');
    versionName = cleanTag;
    fullVersionString = cleanTag;
  } else {
    channel = 'ci';
    versionName = `${baseVersion}-ci.${runNumber}`;
    fullVersionString = versionName;
  }
}

// Compute Android Version Code
function calculateVersionCode(version, buildNum) {
  const parts = version.split('-')[0].split('.');
  const major = parseInt(parts[0] || '1', 10);
  const minor = parseInt(parts[1] || '0', 10);
  const patch = parseInt(parts[2] || '0', 10);
  return major * 100000 + minor * 1000 + patch * 100 + (buildNum % 1000);
}

const versionCode = calculateVersionCode(baseVersion, buildNumber);

// Write src/version.ts
const versionTsPath = path.resolve(__dirname, '../src/version.ts');
const versionContent = `// Auto-generated by build pipeline
export type BuildChannel = 'dev' | 'nightly' | 'rc' | 'stable' | 'ci';

export const APP_VERSION = '${baseVersion}';
export const APP_BUILD_NUMBER = ${buildNumber};
export const APP_VERSION_FULL = '${fullVersionString}';
export const APP_BUILD_CHANNEL: BuildChannel = '${channel}';
export const APP_BUILD_DEV = '${devName}';
export const APP_BRANCH = '${branchName}';
`;
fs.writeFileSync(versionTsPath, versionContent, 'utf8');

// Write build info for Android Gradle
const buildInfoDir = path.resolve(__dirname, '../android/app');
if (fs.existsSync(buildInfoDir)) {
  const buildInfoPath = path.resolve(buildInfoDir, 'build-info.json');
  const buildInfo = {
    version: baseVersion,
    versionName: versionName,
    versionCode: versionCode,
    fullVersionString: fullVersionString,
    channel: channel,
    devName: devName,
    branchName: branchName,
    buildNumber: buildNumber
  };
  fs.writeFileSync(buildInfoPath, JSON.stringify(buildInfo, null, 2) + '\n', 'utf8');
}

console.log(`[Version Tracker] 🚀 Prepared build: ${fullVersionString} (Channel: ${channel}, Code: ${versionCode})`);
