import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkgPath = path.resolve(__dirname, '../package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

// Next build number calculation
const nextBuild = (pkg.buildNumber || 0) + 1;

// Write version.ts with nextBuild so Vite bundles the exact new number
const versionTsPath = path.resolve(__dirname, '../src/version.ts');
const versionContent = `// Auto-generated by build pipeline
export const APP_VERSION = '${pkg.version}';
export const APP_BUILD_NUMBER = ${nextBuild};
export const APP_VERSION_FULL = '${pkg.version}.${nextBuild}';
`;
fs.writeFileSync(versionTsPath, versionContent, 'utf8');

console.log(`[Version Tracker] Prepared build target #${nextBuild} for v${pkg.version}`);
