// Auto-generated by build pipeline
export type BuildChannel = 'dev' | 'nightly' | 'rc' | 'stable' | 'ci';

export const APP_VERSION = '1.2.0';
export const APP_BUILD_NUMBER = '20260926-1341';
export const APP_VERSION_FULL = '1.2.0-dev.jefri.fix-the-agency-dialo.20260926-1341';
export const APP_BUILD_CHANNEL: BuildChannel = 'dev';
export const APP_BUILD_DEV = 'jefri';
export const APP_BRANCH = 'fix-the-agency-dialo';
export const APP_CHANGELOG = `* Merge pull request #154 from jefrimustapa/feat/improve-msm-getter-series-search
* fix(series-search): pass totalSeasons and season-specific year to msm-getter resolver
* Merge pull request #153 from jefrimustapa/feat/series-next-episode-playback
* feat(series): auto-advance play button to next episode when previous episode is completed
* Merge pull request #152 from jefrimustapa/feat/improve-app-visuals
* feat(visuals): standardize purple selection rings, fix placeholder aspect ratios, and optimize TV search card grid
* refactor(ui): standardize media tag badge from FILM to MOVIE (#151)
* feat(msm-getter): improve search accuracy, filter junk trailers, and enforce size thresholds (#150)
* perf(msm-getter): optimize MTProto sender reuse, in-flight coalescing, TCP socket options, and async persistence (#149)
* fix(player): resolve msm-getter pipeline crash and fix MKV resume seeking (#148)
* fix(player): prevent router OOM by avoiding forced transcoding on standard MKVs with audio fallback (#146)
* fix(details): center landscape hero backdrop using object-center matching HeroBanner (#145)
* fix(msm-getter): add startup ffmpeg verification and deferred fallback for audio transcoding (#144)
* fix(msm-getter): harden boot lifecycle, supervisor backoff, and pre-mount ext4 fsck (#143)
* fix(details): eliminate artwork swapping and fit full poster width without horizontal cropping (#142)`;
