// Auto-generated by build pipeline
export type BuildChannel = 'dev' | 'nightly' | 'rc' | 'stable' | 'ci';

export const APP_VERSION = '1.2.0';
export const APP_BUILD_NUMBER = '20260828-2316';
export const APP_VERSION_FULL = '1.2.0-dev.jefri.fix-settings-padding.20260828-2316';
export const APP_BUILD_CHANNEL: BuildChannel = 'dev';
export const APP_BUILD_DEV = 'jefri';
export const APP_BRANCH = 'fix-settings-padding';
